name: "Crear una Issue"
description: "Plantilla para crear una nueva issue"
labels: []
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "Descripción"
      description: "Detalle completo del problema, mejora o tarea. Incluir contexto, objetivo y detalles relevantes."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Criterios de Aceptación (si aplica)"
      description: "Definir las condiciones necesarias para considerar el issue resuelto."
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Pasos para Reproducir (solo para bugs)"
      description: "Lista detallada de pasos para reproducir el problema, en caso de tratarse de un error."
    validations:
      required: false


