services:
  web:
    container_name: web_app_container
    image: uvlhubtortilla/tortilla-hub:dev
    environment:
      FLASK_APP_NAME: "UVLHUB.IO(dev)"
      FLASK_ENV: development
      DOMAIN: localhost
      MARIADB_HOSTNAME: db
      MARIADB_PORT: 3306
      MARIADB_DATABASE: uvlhubdb
      MARIADB_TEST_DATABASE: uvlhubdb_test
      MARIADB_USER: $secrets.MARIADB_USER
      MARIADB_PASSWORD: $secrets.MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD: $secrets.MARIADB_ROOT_PASSWORD
      WORKING_DIR: /app
    expose:
      - "5000"
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "sh", "-c", "sh /app/docker/entrypoints/development_entrypoint.sh" ]
    networks:
      - uvlhub_network

  db:
    container_name: mariadb_container
    environment:
      MARIADB_DATABASE: uvlhubdb
      MARIADB_TEST_DATABASE: uvlhubdb_test
      MARIADB_USER: $secrets.MARIADB_USER
      MARIADB_PASSWORD: $secrets.MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD: $secrets.MARIADB_ROOT_PASSWORD
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network

  nginx:
    container_name: nginx_web_server_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - uvlhub_network

volumes:
  db_data:

networks:
  uvlhub_network: