"""[bot]migration after merging heads

Revision ID: 2102972d6936
Revises: f1778f58af25
Create Date: 2024-12-14 13:59:26.030023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2102972d6936'
down_revision = 'f1778f58af25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.drop_column('constraints_count')
        batch_op.drop_column('average_features_per_model')
        batch_op.drop_column('max_depth')

    with op.batch_alter_table('fm_metrics', schema=None) as batch_op:
        batch_op.drop_column('number_of_features')
        batch_op.drop_column('constraints_count')
        batch_op.drop_column('variability')
        batch_op.drop_column('max_depth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_depth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('variability', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('constraints_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('number_of_features', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_depth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('average_features_per_model', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('constraints_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
