"""empty message

Revision ID: 21fee77ec676
Revises: 363fdf7e6e5c
Create Date: 2024-12-13 09:38:41.939750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fee77ec676'
down_revision = '363fdf7e6e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakenodo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'data_set', ['dataset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakenodo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('dataset_id')

    # ### end Alembic commands ###
