"""Add orcid field to User model

Revision ID: 6f5857a1b32d
Revises: 31ef8ac73964
Create Date: 2024-11-11 13:07:17.952311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5857a1b32d'
down_revision = '31ef8ac73964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orcid', sa.String(length=19), nullable=True))
        batch_op.create_unique_constraint(None, ['orcid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('orcid')

    # ### end Alembic commands ###
