"""created community request to join

Revision ID: bd4d45c05be5
Revises: 002
Create Date: 2024-11-29 20:12:40.918786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4d45c05be5'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_who_wants_to_join_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_who_wants_to_join_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_join_request')
    # ### end Alembic commands ###
