# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: CI/CD Docker Build

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    name: Build and Deploy Docker Containers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t uvlhubtortilla/tortilla-hub:latest .
          docker push uvlhubtortilla/tortilla-hub:latest

      - name: Set up and deploy containers
        run: |
          docker volume create flask_mysql_volume
          docker network create flask_network || true
          docker run -d --name mysql-container --network flask_network \
            -v flask_mysql_volume:/var/lib/mysql \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            -e MYSQL_DATABASE=flask_app \
            mysql:latest
          docker compose -f docker/docker-compose.dev.yml up -d 

